### ISSUE TITLE
Decide whether to use bootstrap or  USWDS 

### ISSUE THREAD

**Issue by navila-luna** [DSACMS/dedupliFHIR#2]
For dedupe, we have to decide whether to use bootstrap or USWDS to make the front end design. While designing the dedupe user interface is not a priority, it is worth noting to make a decision that considers what would make it easier for others interested in dedupe to understand and easily replicate. With this in minds, pros and cons should be listed later on about which approach to take.

**Comment by IsaacMilarky** [comment]
We decided on USWDS
