### ISSUE TITLE
Password Protected PDF in Docs

### ISSUE THREAD

**Issue by alpivonka** [DSACMS/dedupliFHIR#42]
**Describe the bug**
The pdf file contained in the docs directory "deduplifhir_aco_conversation_guide.pdf" is password protected. If this is a public project and this is documentation it should be accessible by all.

**To Reproduce**
Select docs/deduplifhir_aco_conversation_guide.pdf
Download. 
Open and be challenged for a password.

**Expected behavior**
Be able to open without password

**Actual behavior**
Describe how the observed behavior differs from the expected behavior.
![image](https://github.com/DSACMS/dedupliFHIR/assets/4975072/464dc61e-ca71-4964-ad65-58f59c809a87)

![image](https://github.com/DSACMS/dedupliFHIR/assets/4975072/a77f825a-4ea6-46fe-b3a6-504bce6d3675)

![image](https://github.com/DSACMS/dedupliFHIR/assets/4975072/3e52379e-9769-4ad5-865a-fa2eeff6a143)

**Screenshots**

**Device Info:**
 - OS: Windows

**Comment by IsaacMilarky** [comment]
The PDF described is an internal preparatory file for research that's still in draft/actively being worked on, it'll be made public when that portion of research is complete and made public.
