### ISSUE TITLE
Swap actual FHIR and QRDA records for the example.json that is currently used

### ISSUE THREAD

**Issue by decause-gov** [DSACMS/dedupliFHIR#5]
The text we're matching/deduplicating in the project currently is made-up.

We want to use actual FHIR records, and there's a library for synthetically generating such records called Sythea: https://github.com/synthetichealth/synthea

In addition to FHIR records, we would like this same tool to be able to 'speak' other dialiects, since it is a general purpose text matching library. So QRDA files would also be a great datatype to support. QRDA is xml based, pretty sure, but same principles apply...

**Comment by IsaacMilarky** [comment]
We decided to use Synthea and Faker seperatly instead
