### ISSUE TITLE
Create automated tests for Frontend Electron app

### ISSUE THREAD

**Issue by natalialuzuriaga** [DSACMS/dedupliFHIR#64]
**Is your feature request related to a problem? Please describe.**
Currently, there are no tests written for the frontend electron.js desktop app.

**Describe the intended behavior**
As part of development and release, we would like to run end-to-end automated tests for desktop app.

**Describe the solution you'd like**
A suite of tests should be written to test the functionality of the desktop app. Include the tests as part of making releases and in our PR reviews

**Describe alternatives you've considered**
Manual testing is being done at the moment.

Additional Information:
- https://www.electronjs.org/docs/latest/tutorial/automated-testing
- Playwright and WebdriverIO look like the most commonly used testing frameworks for Electron.js apps

**Comment by Firebird1029** [comment]
@IsaacMilarky I saw you created a PR related to this, does this make this ticket obsolete? If not, I was going to take a look at it next!

**Comment by IsaacMilarky** [comment]
> @IsaacMilarky I saw you created a PR related to this, does this make this ticket obsolete? If not, I was going to take a look at it next!

There are currently backend Python tests that are pending a PR merge but this ticket is for developing tests for the Electron frontend. This ticket is specifically for frontend tests. It would be amazing if you wanted to write tests for the electron.js frontend that would be a great feature to have. 

@Firebird1029

**Comment by IsaacMilarky** [comment]
6/28:

- Still a WIP

**Comment by IsaacMilarky** [comment]
7/1:

- Started writing tests 
- Started with basic checks 
- ACTION: file ticket
- Going to use Playwright bc of its GH stars

**Comment by Firebird1029** [comment]
WIP PR: https://github.com/DSACMS/dedupliFHIR/pull/69
    PR still needs to clarify download file system window, and add Github Action script
new issue opened: https://github.com/DSACMS/dedupliFHIR/issues/70
    when viewport height is too low, Submit button is not clickable

**Comment by IsaacMilarky** [comment]
7/8:

- Wrote frontend tests 
- Checking for file download not possible because it is handled by the OS 
- ACTION: continue to work on draft PR and finish tests

**Comment by Firebird1029** [comment]
Github Action script steps for future reference:

```yml
      - name: Install dependencies for tests
        run: npx playwright install --with-deps chromium

      - name: Run frontend tests
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm test
```

**Comment by Firebird1029** [comment]
Restarted PR: https://github.com/DSACMS/dedupliFHIR/pull/71
