### ISSUE TITLE
Implementing App Icon for Electron Desktop App

### ISSUE THREAD

**Issue by CreativeNick** [DSACMS/dedupliFHIR#68]
**Is your feature request related to a problem? Please describe.**
The app icon has been created and now needs to be implemented for the actual electron desktop app.

**Describe the intended behavior**
The app icon should be implemented for MacOS, Windows, and Linux.

**Describe the solution you'd like**
Look into dedupliFHIR repo and Electron App Builder docs to implement logo for each OS.

**Comment by IsaacMilarky** [comment]
7/8

- Still in the process of installing dedupliFHIR
- Will run it on personal computer 
- PR was merged #61 
- ACTION: Make a PR to add the icon to the project

**Comment by IsaacMilarky** [comment]
7/12:

- Facing issues with install
- Going to try both personal and work laptop 
- ACTION: schedule a tech support meeting if needed later next week

**Comment by natalialuzuriaga** [comment]
7/15:
- Scheduling 1x1 with Pat for tech support
- installation blocking so hopefully will get fixed soon 🙏

**Comment by CreativeNick** [comment]
7/18:
- Pull Request opened: https://github.com/DSACMS/dedupliFHIR/pull/98
- Currently waiting for feedback @natalialuzuriaga @IsaacMilarky @decause-gov

**Comment by natalialuzuriaga** [comment]
7/19:
- PR is up!!! Signed off commits too

**Comment by decause-gov** [comment]
7/22:
- Commits are signed. Confirming merge w/ @natalialuzuriaga .
- ACTION: @natalialuzuriaga will confirm the build is working, then merge
- Then, we can close this ticket!

**Comment by CreativeNick** [comment]
7/22
- Merged!
